### PR TITLE
small changes so people can go ahead and test this

### PR DESCRIPTION
**Pull request by BeastlyGhost**
Hi shubs :wave: did some small things here and there, stuff should be on the commit description

I forgot some, so counting with the changes made in the commit description
- Added "Disable Reset Button" and "Flashing Lights" options
- Removed all the Main Weeks except for Tutorial
- added a "layers" object on Stage so you could add below girlfriend (I was going to add the character itself but that's kind of a stretch already)
- made Asset Modifiers work again (as in changing judgement skins, combo, countdown, etc)

### CODE REVIEW

**Comment by Yoshubs** [comment]
I dont really want asset modifiers in this version, I'll have to take a look at the other stuff

**Comment by Yoshubs** [comment]
OH wait do you mean like pixel? yea that's fine just no noteskins like quant and stuff honestly, don't think it would work with the new system

**Comment by BeastlyGhost** [comment]
> OH wait do you mean like pixel? yea that's fine just no noteskins like quant and stuff honestly, don't think it would work with the new system

noteskins and such prob wouldn't but i think as a way to "re-implement" them, they could probably be set by the chart json itself or something similar

**Comment by Yoshubs** [comment]
image
this typo breaks zooming

**Comment by BeastlyGhost** [comment]
oops

**Pull request merged**
